#!/usr/bin/env python3
"""
Network traffic analysis plotting tool for comparing RAAT vs Diretta.

This script parses and compares network packet captures representing input (RAAT)
and output (Diretta) traffic streams. It loads CSV files generated by
capture_comparison.sh to calculate throughput and generate comparison plots showing
both macro-level throughput and micro-level packet spacing/timing.
"""
import argparse
import os
import sys

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# --- Configuration ---
MICRO_SPAN = 0.008  # 8ms Zoom


def load_data(filename):
    """Loads CSV data into a Pandas DataFrame."""
    if not os.path.exists(filename):
        print(f"Error: File '{filename}' not found.")
        sys.exit(1)
    try:
        df = pd.read_csv(filename)
        df.columns = df.columns.str.strip().str.lower()
        return df
    except Exception as e:  # pylint: disable=broad-exception-caught
        print(f"Error loading CSV {filename}: {e}")
        sys.exit(1)


def calculate_throughput(df, window_size='10ms'):
    """
    Calculates throughput in Mbps by resampling the packet sizes over time.

    Assumes 'frame.time_relative' is in seconds.
    """
    time_col = 'frame.time_relative' if 'frame.time_relative' in df.columns else 'time'
    len_col = 'frame.len' if 'frame.len' in df.columns else 'len'

    df_copy = df.copy()
    # Convert relative time to a proper Timedelta index for resampling
    df_copy['time_delta'] = pd.to_timedelta(df_copy[time_col], unit='s')
    df_copy = df_copy.set_index('time_delta')

    # Resample and sum packet lengths (in bytes)
    resampled = df_copy[len_col].resample(window_size).sum().fillna(0)

    # Convert Bytes -> Bits -> Megabits
    # Window size needs to be normalized to seconds to get Mbps rate
    window_seconds = pd.to_timedelta(window_size).total_seconds()
    throughput_mbps = (resampled * 8) / (1_000_000 * window_seconds)

    # Convert index back to seconds (float) for plotting
    time_seconds = resampled.index.total_seconds()

    return time_seconds, throughput_mbps


def find_busiest_window_centered(df, window_span=MICRO_SPAN):
    """
    Finds the window with the most packets and centers it.

    This ensures the micro-view isn't empty and looks nice.
    """
    time_col = 'frame.time_relative' if 'frame.time_relative' in df.columns else 'time'
    times = df[time_col]

    if len(times) < 2 or times.min() >= times.max():
        return 15.0  # safe default start time if data is insufficient

    # Create a simple histogram/density check
    # Bin data into 0.1ms chunks for finer resolution
    bins = np.arange(times.min(), times.max(), 0.0001)
    counts, edges = np.histogram(times, bins=bins)

    # Find the index of the bin with the max packets
    max_idx = np.argmax(counts)

    # The peak time is the center of that bin
    peak_time = (edges[max_idx] + edges[max_idx+1]) / 2

    # Calculate start time so peak is in the middle of the window
    start_time = peak_time - (window_span / 2)

    return start_time


def get_micro_window(raat_df, macro_start, macro_end):
    """Determines the micro window start and end times."""
    time_col = 'frame.time_relative' if 'frame.time_relative' in raat_df.columns else 'time'
    raat_segment = raat_df[
        (raat_df[time_col] >= macro_start) &
        (raat_df[time_col] <= macro_end)
    ]

    if not raat_segment.empty:
        micro_start = find_busiest_window_centered(raat_segment, MICRO_SPAN)
    else:
        micro_start = macro_start + 10

    return micro_start, micro_start + MICRO_SPAN


def configure_axis(ax, title, ylabel, xlabel=None):
    """Sets titles, labels and grids on an axis to avoid repetition."""
    ax.set_title(title, fontsize=14)
    ax.set_ylabel(ylabel)
    if xlabel:
        ax.set_xlabel(xlabel)
    ax.set_yscale('log')
    ax.grid(True, which="both", ls="-", alpha=0.3)


def plot_graphs(raat_df, diretta_df, output_img):
    """Generates the 2x2 comparison plot."""
    # Define a 30s window for the Macro View
    macro_start = 15.0
    macro_end = 45.0

    # --- 1. Micro View Data Preparation (Packet Zoom) ---
    micro_start, micro_end = get_micro_window(raat_df, macro_start, macro_end)
    print(f"Auto-selected Micro Zoom Window: {micro_start:.4f}s to {micro_end:.4f}s")

    # Filter DataFrames for the Micro View
    raat_micro = raat_df[(raat_df['frame.time_relative'] >= micro_start) &
                         (raat_df['frame.time_relative'] <= micro_end)]

    diretta_micro = diretta_df[(diretta_df['frame.time_relative'] >= micro_start) &
                               (diretta_df['frame.time_relative'] <= micro_end)]

    # --- 2. Plotting ---
    fig, axs = plt.subplots(2, 2, figsize=(16, 10))
    fig.suptitle('Network Traffic Analysis: RAAT vs. Diretta (Logarithmic Scale)', fontsize=16)

    # --- Top Left: RAAT Macro (Throughput) ---
    axs[0, 0].plot(
        *calculate_throughput(raat_df, window_size='10ms'),
        color='#E24A33',
        linewidth=1
    )
    configure_axis(
        axs[0, 0],
        'RAAT Input (30s Window): The Sawtooth',
        'Throughput (Mbps) - Log Scale'
    )
    axs[0, 0].set_xlim(macro_start, macro_end)
    axs[0, 0].set_ylim(0.1, 150)

    # --- Top Right: Diretta Macro (Throughput) ---
    axs[0, 1].plot(
        *calculate_throughput(diretta_df, window_size='10ms'),
        color='#348ABD',
        linewidth=1
    )
    configure_axis(
        axs[0, 1],
        'Diretta Output (30s Window): The Flatline',
        'Throughput (Mbps) - Log Scale'
    )
    axs[0, 1].set_xlim(macro_start, macro_end)
    axs[0, 1].set_ylim(0.1, 150)

    # --- Bottom Left: RAAT Micro (Packet Size) ---
    if not raat_micro.empty:
        axs[1, 0].stem(raat_micro['frame.time_relative'], raat_micro['frame.len'],
                       linefmt='#E24A33', markerfmt='o', basefmt=" ")
    configure_axis(
        axs[1, 0],
        f'RAAT Micro-View ({int(MICRO_SPAN * 1000)}ms Zoom): Packet Clumping',
        'Packet Size (Bytes) - Log Scale',
        xlabel='Time (seconds)'
    )
    axs[1, 0].set_xlim(micro_start, micro_end)
    axs[1, 0].set_ylim(40, 2000)

    # --- Bottom Right: Diretta Micro (Packet Size) ---
    if not diretta_micro.empty:
        axs[1, 1].stem(diretta_micro['frame.time_relative'], diretta_micro['frame.len'],
                       linefmt='#348ABD', markerfmt='o', basefmt=" ")
    configure_axis(
        axs[1, 1],
        f'Diretta Micro-View ({int(MICRO_SPAN * 1000)}ms Zoom): Even Spacing',
        'Packet Size (Bytes) - Log Scale',
        xlabel='Time (seconds)'
    )
    axs[1, 1].set_xlim(micro_start, micro_end)
    axs[1, 1].set_ylim(40, 2000)

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.savefig(output_img)
    print(f"\n✅ Graph generated: {output_img}")

    if sys.stdout.isatty() and 'DISPLAY' in os.environ:
        plt.show()


def main():
    """Main function to parse arguments and execute plotting."""
    parser = argparse.ArgumentParser(
        description='Compare network traffic: RAAT input vs. Diretta output'
    )
    parser.add_argument(
        'raat_csv',
        help='Path to the RAAT CSV file'
    )
    parser.add_argument(
        'diretta_csv',
        help='Path to the Diretta CSV file'
    )
    args = parser.parse_args()

    print(f"Loading RAAT data from: {args.raat_csv}")
    raat_df = load_data(args.raat_csv)

    print(f"Loading Diretta data from: {args.diretta_csv}")
    diretta_df = load_data(args.diretta_csv)

    # Determine output image path
    if args.raat_csv.lower().endswith('.csv'):
        output_img = args.raat_csv[:-4] + '_comparison.png'
    else:
        output_img = args.raat_csv + '_comparison.png'

    print("Generating plots...")
    plot_graphs(raat_df, diretta_df, output_img)


if __name__ == "__main__":
    main()
