#!/bin/bash

# A script to install and configure chrony on Arch Linux and its derivatives.

# --- Configuration ---
# Use the NTP pool project for a robust and distributed time source.
# You can change this to a specific pool for your region if desired.
# For example: pool us.pool.ntp.org iburst
NTP_SERVERS="pool pool.ntp.org iburst"

# --- Script Start ---

# 1. Check for Root Privileges
if [ "$EUID" -ne 0 ]; then
  echo "Please run this script as root or with sudo."
  exit 1
fi

echo "--- Installing chrony ---"
# 2. Install chrony using pacman
#    -Syu: Syncs repositories, updates the system, and installs the package.
#    --noconfirm: Skips all confirmation prompts.
pacman -Syu --noconfirm chrony
if [ $? -ne 0 ]; then
    echo "Error: Failed to install chrony. Aborting."
    exit 1
fi

echo "--- Configuring chrony ---"
# 3. Back up the original configuration file if it exists
if [ -f /etc/chrony.conf ]; then
  echo "Backing up existing /etc/chrony.conf to /etc/chrony.conf.bak"
  mv /etc/chrony.conf /etc/chrony.conf.bak
fi

# 4. Create a new chrony.conf
#    Using a heredoc (<<EOF) to write the configuration directly.
cat <<EOF > /etc/chrony.conf
# This file was generated by the chrony installer script.

# Use NTP servers from the pool.ntp.org project.
# 'iburst' sends a burst of packets on startup for faster initial sync.
$NTP_SERVERS

# Step the system clock immediately if the offset is greater than 1.0 second,
# but only for the first three clock updates.
makestep 1.0 3

# Enable kernel synchronization of the real-time clock (RTC).
# This is useful for saving the time to the hardware clock.
rtcsync

# Specify the directory for log files.
logdir /var/log/chrony
EOF

echo "New configuration written to /etc/chrony.conf"

echo "--- Starting and Enabling chrony service ---"
# 5. Enable and start the chronyd service with systemctl
systemctl enable --now chronyd
if [ $? -ne 0 ]; then
    echo "Error: Failed to start or enable the chronyd service."
    exit 1
fi

echo ""
echo "--- Verification ---"
echo "Chrony has been installed, configured, and started."
echo "It may take a minute to synchronize. You can check the status with:"
echo "  chronyc sources"
echo "  systemctl status chronyd"
echo ""
echo "Done!"

sleep 5
chronyc sources
